pipeline:
  name: coinbase-sdk-test
  identifier: coinbasesdktest
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: coinbase-wallet-sdk
        build: <+input>
  stages:
    - stage:
        name: lint-check
        identifier: lintcheck
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Checkout
                  identifier: Checkout
                  spec:
                    uses: actions/checkout@v3
              - step:
                  type: Action
                  name: Checkout node action
                  identifier: Checkout_node_action
                  spec:
                    uses: actions/setup-node@v3
                    with:
                      node-version-file: "'.nvmrc'"
                      cache-dependency-path: "'**/yarn.lock'"
              - step:
                  type: Run
                  name: Install NPM dependencies
                  identifier: Install_NPM_dependencies
                  spec:
                    shell: Sh
                    command: |-
                      cd packages/wallet-sdk
                      yarn install
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Run
                  name: Check ESLint
                  identifier: Check_ESLint
                  spec:
                    shell: Sh
                    command: yarn lint:eslint
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Run
                  name: Check prettier formatting
                  identifier: Check_prettier_formatting
                  spec:
                    shell: Sh
                    command: yarn lint:prettier
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Run
                  name: Runs compile asset script
                  identifier: Runs_compile_asset_script
                  spec:
                    shell: Sh
                    command: node ./compile-assets.js
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Run
                  name: Check Types
                  identifier: Check_Types
                  spec:
                    shell: Sh
                    command: |
                      yarn lint:types
                  when:
                    stageStatus: All
                  failureStrategies: []
